server:
  port: ${SERVER_PORT}
cron:
  buscar:
    estudantes: ${CRON_ESTUDANTES}
file:
  uploadDir: ${UPLOAD_DIR}
auth0:
  audience: ${AUDIENCE}
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        ddl-auto: update
      open-in-view: false
      show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: ${FILE_SIZE_THRESHOLD}
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  sql:
    init:
      mode: always
      platform: ${SQL_PLATFORM}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
